### ISSUE TITLE
kubectl exec & proxy broken after installation of gke example

### ISSUE THREAD

**Issue by BTFO** [GoogleCloudPlatform/terraform-google-nat-gateway#25]
When running a `regional` cluster it seems that both `kubectl exec` and `kubectl proxy` are completely non-functional and broken.

My `terraform.tfvars` looks like the following.

```
region = "europe-west1"
zone = "europe-west1-b"
gke_master_ip = "35.xxx.xxx.xxx"
gke_node_tag = "gke-xxxx-xxx-node"
```

Any suggestions?

**Comment by danisla** [comment]
Looks like this is because regional clusters have multiple masters and the cluster `Endpoint` is actually a load balancer. By inspecting the firewall rule postfixed with `-ssh` you can find all of the master IPs that need special routes to bypass the NAT gateway.

I have a fix and it will be pushed soon! 

Thanks

**Comment by BTFO** [comment]
👍 Thanks a ton!
