### ISSUE TITLE
Multi-region HA using regional managed instance group

### ISSUE THREAD

**Issue by madmod** [GoogleCloudPlatform/terraform-google-nat-gateway#55]
Right now the HA example uses multiple copies of the module which creates a zonal instance group. This could be improved by using a regional manage instance group. I am running into this issue during the creation of modules which would want to use a list of zones. (They create other regional managed instance groups which use the NAT gateways.)

Is there any issue with adding inputs `zonal` and `distribution_policy_zones` like [terraform-google-managed-instance-group has](https://github.com/madmod/terraform-google-managed-instance-group/blob/master/variables.tf#L166-L175)?

How do we maintain backwards compatibility and ensure that we create zonal target tags when we may not know the zones? It may not be possible to determine the zones for the firewall rules if the `distribution_policy_zones` are not explicitly set. Even if we could determine the zones chosen at deploy time, do we have a guarantee that they will not change? (When a zone goes down or during a rolling update for example.)

Right now without `zone` set the `google_compute_route` is created with the default zone of the region. What needs to happen networking wise in order to make this new regional config be HA? Is just making one routing rule per region sufficient? What about instances in other zones? What if the instance in the default zone fails? What if only non default zones are chosen? (By GCP or manually with `distribution_policy_zones`.)

Is there some other common use case that breaks this idea? Like do people use separate subnetworks for different zones or something?

Sorry for my ignorance here. I would appreciate some help investigating this because there are a lot of unknown unknowns for me. If we can figure out a solution to zone discovery I'm happy to make a PR for this.

**Comment by AndrewFarley** [comment]
@madmod So, I'm not sure you understand a few things about how this works, so let me explain (I've learned this the hard way).

1. First, let me start with telling you, the `ha-nat-gateway` example is fully redundant, resilient, and highly available.  At any time you can go kill all except one, or two of those three instances, and the instance tag plus priority-based routing will ensure that your traffic outbound never stops functioning.  I ran a few soak tests from internal to external and saw zero downtime through random scenarios of killing these instances, or downing their network interface, etc.  Please do your own testing if desired, of course one thing it won't do, it automatically fail over a TCP connection to a secondary host if you're streaming data, as it's not a smart multi-homed border gateway or anything.  You'll need to implement a re-try in your application stack.

2. If that point alone wasn't enough, by-design there's a reason this module does NOT use the regional managed instance group.  Primarily because each managed instance group uses ONE single fixed static public IP address.  Using a regional managed instance group, you couldn't do this (to my knowledge).  This is also by design, as this allows you to get a known and static list of your NAT IP addresses which you can use for whitelisting purposes.  With a regional deployment, and/or with trying to "autoscale" the NAT, you would lose the static IP nature of this.

3. With scaling in mind, provided you have a HA deployment (more than one) you can one-at-a-time change the instance type of each of the three NAT gateways.  In Google, changing a managed instance template actually triggers an automatic re-rollout of the new machine type (which is unlike AWS when you change an autoscaling config you have to rollout yourself).  So, all you do is chance one machine type at a time and you can scale up vertically indefinitely.  In my tests, this happens in roughly 1 minute.  On that same token, if you suddenly want more redundancy, you can at any time create a new (fourth, fifth, sixth) NAT gateway module, creating another redundancy and technically adding some scale as well (as new connections outbound would round-robin between similarly prioritized routes).

I hope that makes sense.  I think your topic was raised with the intention to make this "HA" but it's already HA.  

Let me then tackle one of your other ideas... which I've already had myself.  Specifically the one mentioning zone auto-discovery and auto-HA nat.  So, I had this same thought... but this wouldn't be possible before literally a week ago when I got a feature merged into this codebase to "disable" this entire module in a variable.  Leveraging that feature, I would suggest creating a new module for this, call it a `terraform-google-ha-nat-gateway` module that automatically includes 6 copies of this module (6 I think is the current max number of zones in a region), and detects from your current VPC what zones are being used and then deploys a NAT gateway in every one automatically, and then using the module disable on the rest that are unused.  This could be quite handy, might make for a neat module full of modules.  It would be fairly simple to implement, it's something I started trying to conceive, but I realized I needed this module to be disabled to do so, so I focused on that first.  Now that that is upstream, it's now possible to do this.  Feel free!

**Comment by madmod** [comment]
@andrewfarley Thanks for your top notch reply! That all makes sense and answers my questions. I will implement your suggestion of creating another module which contains multiple copies using your new flag to turn them on and off.

**Comment by AndrewFarley** [comment]
@madmod Please share with me/us when you make this module!  :)  I'd fork/use it  :)

**Comment by pbennett** [comment]
@AndrewFarley what about the case where you *have* to use a specific IP address and want fail-over across zones?  ie: Run single NAT gateway for IP address X in zone A, but if zone A goes down, come up in zone B with same IP (and routes all still working).
